version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6381:6379
    volumes:
      - ./redis_data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  redis-test:
    image: redis:alpine
    ports:
      - 6382:6379
    volumes:
      - ./redis_test_data:/var/lib/redis
      - ./redis_test.conf:/usr/local/etc/redis/redis.conf